# Generated by Django 2.2.4 on 2019-08-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haystack_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('other_names', models.CharField(default=' ', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('balance', models.IntegerField(default='0')),
                ('customer_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
